spring.application.name=fastorder

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fastorder
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT
jwt.secret=ZmFzdG9yZGVyLXNlY3JldC1rZXktZXZhbHVhdGlvbi10ZW5pY2EtY2xhdmUtY3J1eGFfc2VjdXJh
jwt.expiration=86400000

server.port=8080
